Propagate GOFIPS140 to rebuilt toolchain
`go tool dist test -rebuild` installs a rebuilt toolchain into
the GOROOT.  This patch propagates GOFIPS140 to the rebuilt toolchain,
and also add a clean-up routine for extracted FIPS snapshot sources
which are otherwise left behind in the readonly modcache.

diff --git a/patches/001-host-fips-auto.patch b/patches/001-host-fips-auto.patch
--- a/patches/001-host-fips-auto.patch
+++ b/patches/001-host-fips-auto.patch
@@ -1,8 +1,8 @@
 diff --git a/src/cmd/dist/build.go b/src/cmd/dist/build.go
-index eacaa53b90..2cb13e7b42 100644
+index 78d55bec55..52630593a0 100644
 --- a/src/cmd/dist/build.go
 +++ b/src/cmd/dist/build.go
-@@ -179,7 +179,7 @@ func xinit() {
+@@ -180,7 +180,7 @@ func xinit() {
  
  	b = os.Getenv("GOFIPS140")
  	if b == "" {
@@ -11,7 +11,7 @@ index eacaa53b90..2cb13e7b42 100644
  	}
  	gofips140 = b
  
-@@ -245,7 +245,8 @@ func xinit() {
+@@ -246,7 +246,8 @@ func xinit() {
  	os.Setenv("GOPPC64", goppc64)
  	os.Setenv("GORISCV64", goriscv64)
  	os.Setenv("GOROOT", goroot)
@@ -21,7 +21,23 @@ index eacaa53b90..2cb13e7b42 100644
  
  	// Set GOBIN to GOROOT/bin. The meaning of GOBIN has drifted over time
  	// (see https://go.dev/issue/3269, https://go.dev/cl/183058,
-@@ -1557,6 +1558,7 @@ func cmdbootstrap() {
+@@ -623,6 +624,15 @@ func setup() {
+ 			}
+ 		}
+ 	}
++
++	// Clean up extracted fips snapshot. This must run before
++	// xremove(obj) because the modcache is readonly, and will
++	// prevent pkg/obj from being cleaned.
++	xatexit(func() {
++		objGopath := pathf("%s/pkg/obj/gopath", goroot)
++		run(goroot, ShowOutput|CheckExit, gorootBinGo, "clean", "-modcache")
++		xremoveall(objGopath)
++	})
+ }
+ 
+ /*
+@@ -1560,6 +1570,7 @@ func cmdbootstrap() {
  	os.Setenv("CC", compilerEnvLookup("CC", defaultcc, goos, goarch))
  	// Now that cmd/go is in charge of the build process, enable GOEXPERIMENT.
  	os.Setenv("GOEXPERIMENT", goexperiment)
@@ -30,10 +46,10 @@ index eacaa53b90..2cb13e7b42 100644
  	goInstall(toolenv(), goBootstrap, append([]string{"-pgo=off"}, toolchain...)...)
  	if debug {
 diff --git a/src/cmd/go/internal/load/godebug.go b/src/cmd/go/internal/load/godebug.go
-index a6bcdad627..e490c52e89 100644
+index 9f8182b82a..b5d4881b3b 100644
 --- a/src/cmd/go/internal/load/godebug.go
 +++ b/src/cmd/go/internal/load/godebug.go
-@@ -73,9 +73,9 @@ func defaultGODEBUG(loaderstate *modload.State, p *Package, directives, testDire
+@@ -73,9 +73,9 @@ func defaultGODEBUG(ld *modload.Loader, p *Package, directives, testDirectives,
  	var m map[string]string
  
  	// If GOFIPS140 is set to anything but "off",
@@ -59,7 +75,7 @@ index 374902eb70..99cbaf2dc3 100644
  [short] skip
  
 diff --git a/src/cmd/go/testdata/script/fipssnap.txt b/src/cmd/go/testdata/script/fipssnap.txt
-index 4d96aedf2a..f0d4771e79 100644
+index 4f2d486c61..31534a1260 100644
 --- a/src/cmd/go/testdata/script/fipssnap.txt
 +++ b/src/cmd/go/testdata/script/fipssnap.txt
 @@ -8,7 +8,7 @@ env GOFIPS140=$snap
@@ -110,10 +126,10 @@ index de50d61208..22bda7ad4b 100644
  }
 diff --git a/src/crypto/internal/fips140deps/hostfips/hostfips.go b/src/crypto/internal/fips140deps/hostfips/hostfips.go
 new file mode 100644
-index 0000000000..12d90a4742
+index 0000000000..84cc1e17c7
 --- /dev/null
 +++ b/src/crypto/internal/fips140deps/hostfips/hostfips.go
-@@ -0,0 +1,60 @@
+@@ -0,0 +1,59 @@
 +// Copyright 2017 The Go Authors. All rights reserved.
 +// Use of this source code is governed by a BSD-style
 +// license that can be found in the LICENSE file.
@@ -121,7 +137,6 @@ index 0000000000..12d90a4742
 +package hostfips
 +
 +import (
-+	"fmt"
 +	"os"
 +	"sync"
 +)
@@ -169,36 +184,47 @@ index 0000000000..12d90a4742
 +		if os.IsNotExist(err) {
 +			return false
 +		}
-+		fmt.Fprintf(os.Stderr, "error reading /proc/sys/crypto/fips_enabled: %v\n", err)
++		os.Stderr.WriteString("error reading /proc/sys/crypto/fips_enabled: " + err.Error() + "\n")
 +		os.Exit(1)
 +	}
 +	return len(data) > 0 && data[0] == '1'
 +}
 diff --git a/src/run.bash b/src/run.bash
-index e774f03b30..6e2e504ab0 100755
+index e774f03b30..37770c78db 100755
 --- a/src/run.bash
 +++ b/src/run.bash
-@@ -37,6 +37,10 @@ if [ ! -f ../bin/go ]; then
+@@ -37,6 +37,14 @@ if [ ! -f ../bin/go ]; then
  fi
  
  export GOENV=off
-+# Prevent the go binary from trying to extract a FIPS snapshot into GOPATH,
-+# which will be set to /nonexist-gopath below. FIPS-specific tests set
-+# GOFIPS140 and GOMODCACHE explicitly in their own environments.
-+export GOFIPS140=off
++# Prevent the go binary from trying to extract a FIPS snapshot
++# into GOPATH, which will be set to /nonexist-gopath below.
++export GOMODCACHE="$(mktemp -d -t run.bash.gomodcache.XXXXXX)"
++if [ $? -ne 0 ]; then
++	echo Could not create modcache in /tmp
++	exit 1
++fi
++trap "../bin/go clean -modcache" EXIT
  eval $(../bin/go tool dist env)
  
  unset CDPATH	# in case user has it set
+@@ -57,4 +65,5 @@ if ulimit -T &> /dev/null; then
+ fi
+ 
+ export GOPATH=/nonexist-gopath
+-exec ../bin/go tool dist test -rebuild "$@"
++# Run dist test as a subprocess to trigger cleanup trap.
++../bin/go tool dist test -rebuild "$@"
 diff --git a/src/go/build/deps_test.go b/src/go/build/deps_test.go
-index e8ba18f2ba..e0fd6a641e 100644
+index 4959a42189..5c909e914d 100644
 --- a/src/go/build/deps_test.go
 +++ b/src/go/build/deps_test.go
-@@ -483,7 +483,8 @@ var depsRules = `
+@@ -488,7 +488,8 @@ var depsRules = `
  
  	internal/byteorder < crypto/internal/fips140deps/byteorder;
  	internal/cpu, internal/goarch < crypto/internal/fips140deps/cpu;
 -	internal/godebug < crypto/internal/fips140deps/godebug;
-+	fmt, sync < crypto/internal/fips140deps/hostfips;
++	os, sync < crypto/internal/fips140deps/hostfips;
 +	internal/godebug, crypto/internal/fips140deps/hostfips < crypto/internal/fips140deps/godebug;
  	time, internal/syscall/windows < crypto/internal/fips140deps/time;
  
@@ -248,10 +274,10 @@ index c563d5b8d9..d0b4be4717 100644
  	t.Logf("%v", cmd.Env)
  	b, e := cmd.CombinedOutput()
 diff --git a/src/cmd/go/script_test.go b/src/cmd/go/script_test.go
-index 088b9a8b5f..7e33b6c786 100644
+index 6033ec420b..3bad3e4f0a 100644
 --- a/src/cmd/go/script_test.go
 +++ b/src/cmd/go/script_test.go
-@@ -255,6 +255,7 @@ func scriptEnv(srv *vcstest.Server, srvCertFile string) ([]string, error) {
+@@ -256,6 +256,7 @@ func scriptEnv(srv *vcstest.Server, srvCertFile string) ([]string, error) {
  		"CMDGO_TEST_RUN_MAIN=true",
  		"HGRCPATH=",
  		"GOTOOLCHAIN=auto",
@@ -259,37 +285,44 @@ index 088b9a8b5f..7e33b6c786 100644
  		"newline=\n",
  	}
  
-diff --git a/src/crypto/internal/fips140deps/hostfips/hostfips.go b/src/crypto/internal/fips140deps/hostfips/hostfips.go
-index 12d90a4742..84cc1e17c7 100644
---- a/src/crypto/internal/fips140deps/hostfips/hostfips.go
-+++ b/src/crypto/internal/fips140deps/hostfips/hostfips.go
-@@ -5,7 +5,6 @@
- package hostfips
- 
- import (
--	"fmt"
- 	"os"
- 	"sync"
- )
-@@ -53,7 +52,7 @@ func checkHostFIPS() bool {
- 		if os.IsNotExist(err) {
- 			return false
+diff --git a/src/cmd/dist/test.go b/src/cmd/dist/test.go
+index 43ac003c79..17aa83dde5 100644
+--- a/src/cmd/dist/test.go
++++ b/src/cmd/dist/test.go
+@@ -158,6 +158,8 @@ func (t *tester) run() {
  		}
--		fmt.Fprintf(os.Stderr, "error reading /proc/sys/crypto/fips_enabled: %v\n", err)
-+		os.Stderr.WriteString("error reading /proc/sys/crypto/fips_enabled: " + err.Error() + "\n")
- 		os.Exit(1)
  	}
- 	return len(data) > 0 && data[0] == '1'
-diff --git a/src/go/build/deps_test.go b/src/go/build/deps_test.go
-index e0fd6a641e..39aa919dbf 100644
---- a/src/go/build/deps_test.go
-+++ b/src/go/build/deps_test.go
-@@ -483,7 +483,7 @@ var depsRules = `
  
- 	internal/byteorder < crypto/internal/fips140deps/byteorder;
- 	internal/cpu, internal/goarch < crypto/internal/fips140deps/cpu;
--	fmt, sync < crypto/internal/fips140deps/hostfips;
-+	os, sync < crypto/internal/fips140deps/hostfips;
- 	internal/godebug, crypto/internal/fips140deps/hostfips < crypto/internal/fips140deps/godebug;
- 	time, internal/syscall/windows < crypto/internal/fips140deps/time;
++	// Propagate GOFIPS140 to rebuilt toolchain binaries.
++	os.Setenv("GOFIPS140", gofips140)
+ 	if t.rebuild {
+ 		t.out("Building packages and commands.")
+ 		// Force rebuild the whole toolchain.
+@@ -184,6 +186,10 @@ func (t *tester) run() {
+ 		}
+ 	}
+ 
++	if err := os.Setenv("GOFIPS140", "off"); err != nil {
++		fatalf("error setting initial GOFIPS140 value for tests")
++	}
++
+ 	t.timeoutScale = 1
+ 	if s := os.Getenv("GO_TEST_TIMEOUT_SCALE"); s != "" {
+ 		t.timeoutScale, err = strconv.Atoi(s)
+diff --git a/src/cmd/go/internal/fips140/fips140.go b/src/cmd/go/internal/fips140/fips140.go
+index 64e8bded32..414baf7278 100644
+--- a/src/cmd/go/internal/fips140/fips140.go
++++ b/src/cmd/go/internal/fips140/fips140.go
+@@ -124,10 +124,10 @@ func Init() {
+ 	// toolchain selection, as the GOEXPERIMENT may be valid for the
+ 	// selected toolchain version.
+ 	if cfg.ExperimentErr == nil && cfg.Experiment.BoringCrypto && Enabled() {
+-		base.Fatalf("go: cannot use GOFIPS140 with GOEXPERIMENT=boringcrypto")
++		base.Fatalf("go: use of GOEXPERIMENT=boringcrypto requires GOFIPS140=off")
+ 	}
+ 	if slices.Contains(cfg.BuildContext.BuildTags, "purego") && Enabled() {
+-		base.Fatalf("go: cannot use GOFIPS140 with the purego build tag")
++		base.Fatalf("go: use of purego build tag requires GOFIPS140=off")
+ 	}
+ }
  
